# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"


command:
  build:
    - "ls -la"
    - "whoami"
    - "sudo npm install gulp-cli -g"
    - "npm install"
    - "gulp build"

  dev:
    - "D:gulp watch"

  test:
    - "/opt/node_modules/.bin/codeceptjs run -c /opt/test/codecept.conf.js"